# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(max_length=10000, primary_key=True, serialize=False, verbose_name='userid')),
            ],
        ),
    ]
