# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='pass', max_length=10000),
        ),
    ]
