# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='word_reading_ability',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
