# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171022_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermoviemap',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='usermoviemap',
            old_name='user_id',
            new_name='user',
        ),
    ]
