# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171021_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='password', max_length=10000),
            preserve_default=False,
        ),
    ]
