# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usermedoids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('artist', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
