# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usermedoids'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='authenticated',
            field=models.IntegerField(default=0),
        ),
    ]
