# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20171022_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField()),
                ('hyperlink', models.CharField(max_length=4000)),
                ('image_hyperlink', models.CharField(max_length=4000)),
            ],
        ),
    ]
