# _*_ coding: utf_8 _*_
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class UserProfile(models.Model):
	user_id = models.CharField(('userid'), primary_key=True, max_length=10000)
	word_reading_ability = models.IntegerField()
	white_wine_liking = models.IntegerField()
	weight = models.IntegerField()
	vitamin_e = models.IntegerField()
	vitamin_d = models.IntegerField()
	vitamin_b12 = models.IntegerField()
	vitamin_a = models.IntegerField()
	type_2_diabetes = models.IntegerField()
	smoking_behavior = models.IntegerField()
	smell_sensitivity_for_malt = models.IntegerField()
	skin_pigmentation = models.IntegerField()
	reward_dependence = models.IntegerField()
	response_to_vitamin_e_supplementation = models.IntegerField()
	red_wine_liking = models.IntegerField()
	red_hair = models.IntegerField()
	reading_and_spelling_ability = models.IntegerField()
	protein_intake = models.IntegerField()
	prostate_cancer = models.IntegerField()
	phosphorus = models.IntegerField()
	peanuts_allergy = models.IntegerField()
	pancreatic_cancer = models.IntegerField()
	openness = models.IntegerField()
	novelty_seeking = models.IntegerField()
	nicotine_dependence = models.IntegerField()
	neuroticism = models.IntegerField()
	myocardial_infarction = models.IntegerField()
	motion_sickness = models.IntegerField()
	morning_person = models.IntegerField()
	milk_allergy = models.IntegerField()
	male_pattern_baldness_aga = models.IntegerField()
	magnesium = models.IntegerField()
	lung_cancer = models.IntegerField()
	longevity = models.IntegerField()
	lobe_size = models.IntegerField()
	liver_cancer = models.IntegerField()
	iron = models.IntegerField()
	hearing_function = models.IntegerField()
	harm_avoidance = models.IntegerField()
	handedness = models.IntegerField()
	gastric_cancer = models.IntegerField()
	gambling = models.IntegerField()
	freckles = models.IntegerField()
	folate = models.IntegerField()
	eye_color = models.IntegerField()
	extraversion = models.IntegerField()
	endurance_performance = models.IntegerField()
	egg_allergy = models.IntegerField()
	depression = models.IntegerField()
	conscientiousness = models.IntegerField()
	colorectal_cancer = models.IntegerField()
	childhood_intelligence = models.IntegerField()
	carbohydrate_intake = models.IntegerField()
	calcium = models.IntegerField()
	caffeine_metabolite_ratio = models.IntegerField()
	caffeine_consumption = models.IntegerField()
	breast_cancer = models.IntegerField()
	bmi = models.IntegerField()
	black_hair = models.IntegerField()
	bitter_taste = models.IntegerField()
	beta_carotene = models.IntegerField()
	beard_thickness = models.IntegerField()
	anger = models.IntegerField()
	alpha_linolenic_acid = models.IntegerField()
	alcohol_drinking_behavior = models.IntegerField()
	agreeableness = models.IntegerField()
	cluster_name = models.CharField()


