# _*_ coding: utf_8 _*_
from __future__ import unicode_literals

from django.db import models


# Create your models here.

class UserProfile(models.Model):
    user_id = models.CharField(('userid'), primary_key=True, max_length=10000)
    word_reading_ability = models.IntegerField(default=0)
    white_wine_liking = models.IntegerField(default=0)
    weight = models.IntegerField(default=0)
    vitamin_e = models.IntegerField(default=0)
    vitamin_d = models.IntegerField(default=0)
    vitamin_b12 = models.IntegerField(default=0)
    vitamin_a = models.IntegerField(default=0)
    type_2_diabetes = models.IntegerField(default=0)
    smoking_behavior = models.IntegerField(default=0)
    smell_sensitivity_for_malt = models.IntegerField(default=0)
    skin_pigmentation = models.IntegerField(default=0)
    reward_dependence = models.IntegerField(default=0)
    response_to_vitamin_e_supplementation = models.IntegerField(default=0)
    red_wine_liking = models.IntegerField(default=0)
    red_hair = models.IntegerField(default=0)
    reading_and_spelling_ability = models.IntegerField(default=0)
    protein_intake = models.IntegerField(default=0)
    prostate_cancer = models.IntegerField(default=0)
    phosphorus = models.IntegerField(default=0)
    peanuts_allergy = models.IntegerField(default=0)
    pancreatic_cancer = models.IntegerField(default=0)
    openness = models.IntegerField(default=0)
    novelty_seeking = models.IntegerField(default=0)
    nicotine_dependence = models.IntegerField(default=0)
    neuroticism = models.IntegerField(default=0)
    myocardial_infarction = models.IntegerField(default=0)
    motion_sickness = models.IntegerField(default=0)
    morning_person = models.IntegerField(default=0)
    milk_allergy = models.IntegerField(default=0)
    male_pattern_baldness_aga = models.IntegerField(default=0)
    magnesium = models.IntegerField(default=0)
    lung_cancer = models.IntegerField(default=0)
    longevity = models.IntegerField(default=0)
    lobe_size = models.IntegerField(default=0)
    liver_cancer = models.IntegerField(default=0)
    iron = models.IntegerField(default=0)
    hearing_function = models.IntegerField(default=0)
    harm_avoidance = models.IntegerField(default=0)
    handedness = models.IntegerField(default=0)
    gastric_cancer = models.IntegerField(default=0)
    gambling = models.IntegerField(default=0)
    freckles = models.IntegerField(default=0)
    folate = models.IntegerField(default=0)
    eye_color = models.IntegerField(default=0)
    extraversion = models.IntegerField(default=0)
    endurance_performance = models.IntegerField(default=0)
    egg_allergy = models.IntegerField(default=0)
    depression = models.IntegerField(default=0)
    conscientiousness = models.IntegerField(default=0)
    colorectal_cancer = models.IntegerField(default=0)
    childhood_intelligence = models.IntegerField(default=0)
    carbohydrate_intake = models.IntegerField(default=0)
    calcium = models.IntegerField(default=0)
    caffeine_metabolite_ratio = models.IntegerField(default=0)
    caffeine_consumption = models.IntegerField(default=0)
    breast_cancer = models.IntegerField(default=0)
    bmi = models.IntegerField(default=0)
    black_hair = models.IntegerField(default=0)
    bitter_taste = models.IntegerField(default=0)
    beta_carotene = models.IntegerField(default=0)
    beard_thickness = models.IntegerField(default=0)
    anger = models.IntegerField(default=0)
    alpha_linolenic_acid = models.IntegerField(default=0)
    alcohol_drinking_behavior = models.IntegerField(default=0)
    agreeableness = models.IntegerField(default=0)
    cluster_name = models.CharField(max_length=10000, null=True, blank=True)
